[phases.setup]
nixPkgs = ["nodejs"]
[phases.install]
dependsOn = ["setup"]
cmd = "cd backend && npm install"
[phases.build]
dependsOn = ["install"]
cmd = "echo build ok"
[start]
cmd = "cd backend && node index.js"